# Generated by Django 4.0.5 on 2023-09-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_productcategory_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductDescription',
            field=models.TextField(max_length=254),
        ),
    ]
