# Generated by Django 4.0.5 on 2023-09-19 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_products_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
